name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to S3
      run: aws s3 sync . s3://rishabh-portfolio --delete

      env:
        SOURCE_DIR: 'dist'
        AWS_S3_BUCKET: 'rishabh-portfolio'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'

    - name: Set correct MIME types for JavaScript files
      run: |
        aws s3 cp s3://rishabh-portfolio/dist/ s3://rishabh-portfolio/dist/ --recursive --metadata-directive REPLACE --content-type application/javascript
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1' 
