name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region 'us-east-1' # Update with your region

    - name: Sync to S3 with correct MIME types
      run: |
        aws s3 sync dist s3://rishabh-portfolio/ --acl public-read --delete --exact-timestamps \
          --content-type 'application/javascript' --exclude "*.html" --exclude "*.css"
        aws s3 sync dist s3://rishabh-portfolio/ --acl public-read --delete --exact-timestamps \
          --content-type 'text/html' --exclude "*" --include "*.html"
        aws s3 sync dist s3://rishabh-portfolio/ --acl public-read --delete --exact-timestamps \
          --content-type 'text/css' --exclude "*" --include "*.css"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
